baseURL = "https://corax.com.cn"
languageCode = "en-us"
title = "Corax の Bathmos"
# theme         = "roxo-hugo"
summarylength = 25

# Site Menus
[menu]
# Navbar Menus
[[menu.nav]]
name = "🏠Home"
url = ""
weight = 1
[[menu.nav]]
name = "📄About"
url = "about"
weight = 2
[[menu.nav]]
name = "🔗Friend"
url = "friend"
weight = 3
[[menu.nav]]
name = "🕊Blog"
url = "blog"
weight = 4
[[menu.nav]]
name = "Get in touch"
url = "contact"
weight = 5

# Site Params
[params]
dateFormat = "26 FEB 1994"
logo = "images/logo.png"
# Meta data
author = "Corax"
description = "Roxo Hugo themes | Design Agency Template by StaticMania"
# Google Analitycs
googleAnalitycsID = "Your ID"
# We're using formspree.io for form handling, paste your formspree url below
fabform = "https://fabform.io/f/USAg2Jl"

# Contact Form
[params.contactForm]
placeholder_about_the_project = "Your Advice"
placeholder_email = "Email"
placeholder_first_name = "First Name"
placeholder_last_name = "Last Name"
send_message = "Send Message"

# Navbar Action Button
[params.navAction]
name = "Get in touch"
status = true
url = "contact"

# Banner Section
[params.banner]
background_image = "images/backgrounds/bochi.jpg"
enable = true
heading = "ようこそCoraxの小さな巣へ"
primary_button = "See My Friend"
primary_button_url = "friend"
secondary_button = "Contact with Me"
secondary_button_url = "contact"
tagline = "最怕你一生碌碌无为，还安慰自己平凡可贵"

[params.call_to_action]
background_image = "images/backgrounds/cta-background.jpg"
enable = true
primary_button = "Submit Advice"
primary_button_url = "contact"
secondary_button = "See My Friend"
secondary_button_url = "friend"
title = "Happy Learning Happy Playing"

[params.footer]
# Footer Contact Info
[params.footer.contactInfo]
address = "JiangSu NanJing University"
email = "2631197015@qq.com"
title = "Contact Info"
# Footer Sitemap
[params.footer.sitemap]
title = "Sitemap"
[[params.footer.sitemap.link]]
name = "About Me"
url = "about"
[[params.footer.sitemap.link]]
name = "Friends"
url = "friend"
[[params.footer.sitemap.link]]
name = "Blog"
url = "blog"
[[params.footer.sitemap.link]]
name = "Contact"
url = "contact"
# Footer Social Media
[params.footer.social]
title = "Social Media"
[[params.footer.social.link]]
name = "Bilibili"
url = "https://space.bilibili.com/330247538?spm_id_from=333.1007.0.0"
[[params.footer.social.link]]
name = "Github"
url = "https://github.com/KYCoraxxx"
# Footer Service
[params.footer.service]
description = "Communication<br>Exchanging Ideas<br>Learning and Playing joyfully"
title = "This site is built for"
